services:
  napier-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./napier_config.json:/app/napier_config.json
      - ./temp_images:/app/temp_images
    restart: unless-stopped